[versions]
guava = "31.1-jre"
jetbrains-annotations = "23.0.0"
junit = "5.9.0"
logback = "1.4.1"
lombok-plugin = "9.5.0"
mail-srs = "1.0.0"
mschout-conventions = "0.7.0"
netty = "4.1.82.Final"
netty-codec-netstring = "0.6.1"
picocli = "4.6.3"
slf4j = "2.0.1"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
mail-srs = { module = "io.github.mschout:mail-srs-java", version.ref = "mail-srs" }
netty-all = { module = "io.netty:netty-all", version.ref = "netty" }
netty-codec-netstring = { module = "io.github.mschout:netty-codec-netstring", version.ref = "netty-codec-netstring" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombok-plugin" }
mschout-all-conventions = { id = "io.github.mschout.all-conventions", version.ref = "mschout-conventions" }
mschout-maven-publish-conventions = { id = "io.github.mschout.maven-publish-conventions", version.ref = "mschout-conventions" }
